name: Update streak stats

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&background=040B1A&hide_border=true&border=C8983E&ring=C8983E&fire=C8983E&currStreakNum=E8D5B0&sideNums=E8D5B0&currStreakLabel=C8983E&sideLabels=C8983E&dates=A68A52
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
